[package]
name = "sibyl-test"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
sibyl = { version = "0.6.22", features = ["tokio", "nonblocking"] }
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
